[package]
name          = "minicbor"
version       = "2.2.2"
authors       = ["Toralf Wittner <tw@dtex.org>"]
license       = "BlueOak-1.0.0"
edition       = "2024"
description   = "A small CBOR codec suitable for no_std environments."
repository    = "https://github.com/twittner/minicbor"
keywords      = ["cbor", "minicbor", "serialization", "encoding", "no_std"]
categories    = ["encoding"]

[package.metadata.docs.rs]
features = ["std", "derive", "half"]

[features]
alloc  = []
std    = ["alloc"]
derive = ["minicbor-derive"]
certified_subset = []

[dependencies]
minicbor-derive = { version = "0.19.4", path = "../minicbor-derive", optional = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dev-dependencies]
minicbor = { path = ".", features = ["std"] }
